---
url:
  root: 'https://lms.iiitb.ac.in/moodle'
  login: "/login/index.php"
  home: "/my"

patterns:
  root: 'https://lms.iiitb.ac.in/moodle'
  login: '/login/index.php'
  home: '/my'
  course: '/course'
  forum: '/mod/forum'
  material: '/mod/folder'
  activity: '/mod/assign'

flags:
  allowInsecure: true

status:
  loggedOut: 'You are not logged in.'
  loggedIn: 'You are logged in as '

params:
  onlineTimeout: 3000

response:
  user:
    login:
      success: { context: 'login', status: 'authenticated', code: 0 }
      invalidCreds: { context: 'login', status: 'invalidCredentials', code: 1 }
      headerMismatch: { context: 'login', status: 'headerMismatch', code: 2 }
      cannotConnect: { context: 'login', status: 'cannotConnect', code: 3 }
      unknownError: { context: 'login', status: 'Error', error: null, code: 4 }
    getCourseContent:
      success: { context: 'course', status: 'success', data: { forums: null, activities: null, materials: null }, code: 0 }
      cannotConnect: { context: 'course', status: 'cannotConnect', code: 1, error: null }
      forumSuccess: { context: 'forumList', status: 'success', data: { names: null, links: null }, code: 0 }
      noForum: { context: 'forumList', status: 'noForum', code: 1 }
      activitySuccess: { context: 'activityList', status: 'success', data: { summary: null, links: null, names: null, descriptions: null }, code: 0 }
      noActivity: { context: 'activityList', status: 'noActivity', code: 1 }
      materialSuccess: { context: 'materialList', status: 'success', data: { summary: null, links: null, names: null, descriptions: null }, code: 0 }
      noMaterial: { context: 'materialList', status: 'noMaterial', code: 1 }
    getHomeContent:
      success: { context: 'home', status: 'success', data: { courseList: null, privateFiles: null }, code: 0 }
      cannotConnect: { context: 'home', status: 'cannotConnect', error: null, code: 1 }
      unknownError: { context: 'home', status: 'error', error: null, code: 2 }
      data:
        courseDataSuccess: { context: 'courseList', status: 'success', data: { links: null, names: null }, code: 0 }
        filesDataSuccess: { context: 'privateFiles', status: 'success', data: { links: null, names: null }, code: 0 }

eventFlags:
  user:
    getCourses:
      success: { status: 'success', code: 0 }
      unknownError: { status: 'error', code: 1 }

    getPrivateFiles:
      success: { status: 'success', code: 0 }
      unknownError: { status: 'error', code: 1 }

    isLoggedin:
      success: { status: 'success', code: 0}
      cannotConnect: { status: 'cannotConnect', code: 1 }
      nullValue: { status: 'nullValue', error: 2 }
      unknownError: { status: 'Error', code: 3 }

  activity: # activity class
    getContent:
      success: { status: 'success', code: 0 }
      noContent: { status: 'noContent', code: 1 }
      cannotConnect: { status: 'cannotConnect', code: 2 }
      unknownError: { status: 'Error', code: 3 }

  material: # material class
    getContent:
      success: { status: 'success', code: 0 }
      noContent: { status: 'noContent', code: 1 }
      cannotConnect: { status: 'cannotConnect', code: 2 }
      unknownError: { status: 'Error', code: 3 }

  course:
    forum:
      success: { status: 'success', code: 0 }
      noForum: { status: 'noForum', code: 1 }
      cannotConnect: { status: 'cannotConnect', code: 2 }
      unknownError: { status: 'Error', code: 3 }

    activity:
      success: { status: 'success', code: 0 }
      noActivity: { status: 'noActivity', code: 1 }
      cannotConnect: { status: 'cannotConnect', code: 2 }
      unknownError: { status: 'Error', code: 3 }

    material: # course -> getMaterial
      success: { status: 'success', code: 0 }
      noMaterial: { status: 'noMaterial', code: 1 }
      cannotConnect: { status: 'cannotConnect', code: 2 }
      unknownError: { status: 'Error', code: 3 }

selector:
  site:
    pageTitle: ".headermenu"
    userStatus: ".logininfo"
    loggedOut: 'You are not logged in.'
    loggedIn: 'You are logged in as '

  user:
    privateFiles:
      fileList: div[id^="private_files_tree_"]
      fileLink: a @href
      fileName: a

    courseList:
      courseList: "#page-content"
      courseLink: ".corner-box .content .course_list h2 @href"
      courseName: ".corner-box .content .course_list h2"

  activity:
    activity: "#region-main"
    title: "#region-main > div > div > h2"
    intro: "#intro > div > p"
    submissionR: "div > div > div.submissionstatustable > div > table > tbody > tr > td.cell.c1.lastcol"
    submissionL: "div > div > div.submissionstatustable > div > table > tbody > tr > td.cell.c0"
    feedbackR: "div > div > div.feedback > div > table > tbody > tr > td.cell.c1.lastcol"
    feedbackL: "div > div > div.feedback > div > table > tbody > tr > td.cell.c0"
    files: "div > div > div.submissionstatustable > div > table > tbody > tr > td.cell.c1.lastcol @href"

  material:
    content: ".foldertree"
    link: "* > a @href"
    name: "* > a"

  course:
    activity:
      activity: ".course-content"
      summary: "div.content > div > div > p"
      link: ".modtype_assign > div > div > div:nth-child(2) > div.activityinstance > a @href"
      name: ".modtype_assign > div > div > div:nth-child(2) > div.activityinstance > a"
      desc: ".modtype_assign > div > div > div:nth-child(2) > div.contentafterlink > div > div > p"

    forum:
      forum: ".course-content"
      link: ".modtype_forum > div > div > div:nth-child(2) > div > a @href"
      name: ".modtype_forum > div > div > div:nth-child(2) > div > a"


    material:
      material: ".course-content"
      summary: "div.content > div > div > p"
      link: ".modtype_folder a @href"
      name: ".modtype_folder a"
      desc: ".contentafterlink p"
